@ECHO OFF

:: Generate the file ..\README_UCP.txt from the wiki files

SET _README="..\README_UCP.txt"
@echo "$ Autogenerated on %DATE% at %TIME% $ > %_README%

for %%g in ( home important_information changelist installation uninstall ) do (
type %%g.wiki >> %_README%
)
